name: Pling Release Package Upload

on:
  push:
    tags:
      - "release*"

jobs:
  upload-to-pling:
    uses: ruinivist/kde-6-widget-starter/.github/workflows/reusable-pling-upload.yml@main
    with:
      project-id: "2355726"
    secrets:
      PLING_USERNAME: ${{ secrets.PLING_USERNAME }}
      PLING_PASSWORD: ${{ secrets.PLING_PASSWORD }}
